'use client';
import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';
import { categories } from '@/lib/categories';
import { submitPrompt } from '@/lib/prompts-service';
import { useAuth } from '@/lib/auth-context';
import type { Category } from '@/lib/types';
import { toast } from 'sonner';
export function SubmitForm() { const { user } = useAuth(); const router = useRouter(); const [title, setTitle] = useState(''); const [content, setContent] = useState(''); const [category, setCategory] = useState<Category>('Anime'); const [tags, setTags] = useState(''); async function onSubmit(e: FormEvent) { e.preventDefault(); if (!user) { toast.error('Sign in to submit prompts'); router.push('/login'); return; } try { const id = await submitPrompt({ title, content, category, tags: tags.split(',').map((t) => t.trim()).filter(Boolean), authorId: user.uid, authorName: user.displayName || user.email?.split('@')[0] || 'Creator' }); toast.success('Prompt submitted'); router.push(`/prompts/${id}`); } catch (error) { toast.error(error instanceof Error ? error.message : 'Submission failed'); } } return <form onSubmit={onSubmit} className="glass mx-auto max-w-3xl rounded-[2rem] p-8"><h1 className="text-4xl font-black">Submit a prompt</h1><p className="mt-3 text-slate-400">Publish a detailed, reusable image prompt with tags and category metadata.</p><div className="mt-8 space-y-5"><input required value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Prompt title" className="w-full rounded-2xl border-white/10 bg-white/5 text-white" /><select value={category} onChange={(e) => setCategory(e.target.value as Category)} className="w-full rounded-2xl border-white/10 bg-slate-950 text-white">{categories.map((c) => <option key={c.name}>{c.name}</option>)}</select><textarea required rows={10} value={content} onChange={(e) => setContent(e.target.value)} placeholder="Write the full prompt..." className="w-full rounded-2xl border-white/10 bg-white/5 text-white" /><input value={tags} onChange={(e) => setTags(e.target.value)} placeholder="tags, separated, by commas" className="w-full rounded-2xl border-white/10 bg-white/5 text-white" /></div><button className="mt-6 rounded-2xl bg-gradient-to-r from-neon-blue to-neon-purple px-8 py-3 font-semibold">Publish prompt</button></form>; }
