import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { PromptActions } from '@/components/prompt-actions';
import { PromptCard } from '@/components/prompt-card';
import { samplePrompts } from '@/lib/sample-prompts';
import { formatNumber, siteUrl } from '@/lib/utils';
import { Eye, Heart, Star, UserRound } from 'lucide-react';

type Props = { params: Promise<{ id: string }> };
export async function generateStaticParams() { return samplePrompts.slice(0, 120).map((prompt) => ({ id: prompt.id })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { id } = await params; const prompt = samplePrompts.find((p) => p.id === id); return prompt ? { title: prompt.title, description: prompt.content.slice(0, 155), openGraph: { title: prompt.title, description: prompt.content.slice(0, 155), url: `${siteUrl()}/prompts/${prompt.id}` } } : { title: 'Prompt not found' }; }
export default async function PromptDetailsPage({ params }: Props) { const { id } = await params; const prompt = samplePrompts.find((p) => p.id === id); if (!prompt) notFound(); const similar = samplePrompts.filter((p) => p.category === prompt.category && p.id !== prompt.id).slice(0, 3); return <main className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><div className="grid gap-8 lg:grid-cols-[1fr_360px]"><article className="glass rounded-[2rem] p-8"><div className="mb-6 flex flex-wrap items-center gap-3"><span className="rounded-full bg-neon-blue/15 px-3 py-1 text-sm text-neon-blue">{prompt.category}</span>{prompt.featured && <span className="rounded-full bg-purple-500/20 px-3 py-1 text-sm text-purple-200">Featured</span>}</div><h1 className="text-4xl font-black sm:text-5xl">{prompt.title}</h1><div className="mt-5 flex flex-wrap gap-5 text-sm text-slate-400"><span><Heart className="mr-1 inline h-4 w-4" />{formatNumber(prompt.likes)} likes</span><span><Star className="mr-1 inline h-4 w-4" />{formatNumber(prompt.favorites)} favorites</span><span><Eye className="mr-1 inline h-4 w-4" />{formatNumber(prompt.views)} views</span></div><div className="mt-8 rounded-3xl border border-white/10 bg-black/30 p-6"><pre className="whitespace-pre-wrap font-sans text-base leading-8 text-slate-200">{prompt.content}</pre></div><div className="mt-6"><PromptActions promptId={prompt.id} content={prompt.content} /></div></article><aside className="space-y-5"><div className="glass rounded-3xl p-6"><UserRound className="h-10 w-10 text-neon-blue" /><h2 className="mt-4 text-xl font-bold">{prompt.authorName}</h2><p className="mt-2 text-sm text-slate-400">Verified PromptHub creator. Follow creators from the dashboard to keep a personalized feed.</p><button className="mt-5 w-full rounded-2xl bg-white py-3 font-semibold text-ink">Follow creator</button></div><div className="glass rounded-3xl p-6"><h2 className="font-bold">Tags</h2><div className="mt-4 flex flex-wrap gap-2">{prompt.tags.map((tag) => <span key={tag} className="rounded-full border border-white/10 px-3 py-1 text-sm text-slate-300">#{tag}</span>)}</div></div></aside></div><section className="mt-14"><h2 className="text-3xl font-bold">Similar prompts</h2><div className="mt-6 grid gap-5 md:grid-cols-3">{similar.map((item, i) => <PromptCard key={item.id} prompt={item} index={i} />)}</div></section></main>; }
